-- CreateEnum
CREATE TYPE "auth"."UserRole" AS ENUM ('SUPER_ADMIN', 'ADMIN', 'PRINCIPAL', 'TEACHER', 'STUDENT', 'PARENT');

-- CreateTable
CREATE TABLE "auth"."USERS" (
    "ID" SERIAL NOT NULL,
    "ACTIVE" BOOLEAN NOT NULL DEFAULT true,
    "ENTRY_USER" INTEGER,
    "ENTRY_DATE" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "UPDATE_USER" INTEGER,
    "UPDATE_DATE" TIMESTAMP(3),
    "FULL_NAME" TEXT NOT NULL,
    "EMAIL" TEXT NOT NULL,
    "PASSWORD" TEXT NOT NULL,
    "ROLE" "auth"."UserRole" NOT NULL DEFAULT 'STUDENT',

    CONSTRAINT "USERS_pkey" PRIMARY KEY ("ID")
);

-- CreateIndex
CREATE UNIQUE INDEX "USERS_EMAIL_key" ON "auth"."USERS"("EMAIL");
