-- CreateTable
CREATE TABLE "auth"."REFRESH_TOKENS" (
    "ID" SERIAL NOT NULL,
    "TOKEN_HASH" TEXT NOT NULL,
    "USER_ID" INTEGER NOT NULL,
    "EXPIRES_AT" TIMESTAMP(3) NOT NULL,
    "REVOKED" BOOLEAN NOT NULL DEFAULT false,
    "CREATED_AT" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "REFRESH_TOKENS_pkey" PRIMARY KEY ("ID")
);

-- CreateIndex
CREATE INDEX "REFRESH_TOKENS_USER_ID_idx" ON "auth"."REFRESH_TOKENS"("USER_ID");

-- CreateIndex
CREATE INDEX "REFRESH_TOKENS_TOKEN_HASH_idx" ON "auth"."REFRESH_TOKENS"("TOKEN_HASH");

-- AddForeignKey
ALTER TABLE "auth"."REFRESH_TOKENS" ADD CONSTRAINT "REFRESH_TOKENS_USER_ID_fkey" FOREIGN KEY ("USER_ID") REFERENCES "auth"."USERS"("ID") ON DELETE CASCADE ON UPDATE CASCADE;
